language: node_js
os: linux
dist: bionic
node_js:
  - "18.18"

cache:
  directories:
    - "backend/node_modules"
    - "frontend/node_modules"

install:
  - npm run backend-install
  - npm run frontend-install

script:
  - npm run build
  - npm run run-all
